<h3 style="color:#6FA8DC; font-weight:bold">Creating Numpy Arrays</h3>

In [2]:
# step-1 is to import numpy
import numpy as np

In [3]:
# np.array -> to create numpy array
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
# to store this array in variable
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [5]:
# to see its type
print(type(a))

<class 'numpy.ndarray'>


In [6]:
#dtype
np.array([1,2,3,4], dtype=float)

array([1., 2., 3., 4.])

<h5 style="color:#B58AC6; font-weight:bold;">arange → to create array within a range</h5>

In [7]:
np.arange(1,11) #end is excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])