<h3 style="color:#6FA8DC; font-weight:bold">Array Attributes</h3>

In [3]:
import numpy as np

In [14]:
# initially creating 3 arrays
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2) #3D matrix / 3D Tensor

print(a1)
print(a2)
print(a3)   

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


<br>

<h5 style="color:#78B89A; font-weight:bold;">ndim → tell dimension of array</h5>

In [6]:
print(a2.ndim)

2


<br>

<h5 style="color:#78B89A; font-weight:bold;">shape → to see no of items, no of rows and no of columns in an array</h5>

In [9]:
print(a1.shape) #output = (10,) -> means 10 items in single row
print(a2.shape) #output = (3,4) -> means 3 rows and 4 columns
print(a3.shape) #output = (2, 2, 2) -> means 2 layers, each with 2 rows and 2 columns

(10,)
(3, 4)
(2, 2, 2)


<br>

<h5 style="color:#78B89A; font-weight:bold;">size → size tells you the total number of elements in an array</h5>

In [10]:
print(a2.size)

12


<br>

<h5 style="color:#78B89A; font-weight:bold;">itemsize → itemsize tells you the number of bytes used by each element in an array</h5>

In [ ]:
print(a3.itemsize) #output = 8, since each element in a3 is a 64-bit float (8 bytes)

8


<br>

<h5 style="color:#78B89A; font-weight:bold;">dtype → dtype means data type. It tells you what type of data the elements in an array contain and how they are stored in memory.</h5>

In [15]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

# output = int64
#          float64
#          int64


int64
float64
int64


<h3 style="color:#6FA8DC; font-weight:bold">Changing Datatype</h3>

In [ ]:
#astype
print(a3.astype(np.int32))

# why to use?
# see earlier we have int64 datatype in a3 as deafult but lets say we want to store age in a3 and since we know int64 is used to store big no.'s and take 64bit of memory and the task is to store age only then why to waste memory and conveting into int32

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
