<h3 style="color:#6FA8DC; font-weight:bold">04. ML Pipelines — Prediction WITHOUT vs WITH Pipeline</h3>

<h5 style="color:#78B89A; font-weight:bold;">WITHOUT Pipeline</h5>

```text
New data
   ↓
Manually repeat SAME preprocessing
   ↓
Model.predict()
   ↓
Prediction
```

<h5 style="color:#78B89A; font-weight:bold;">WITH Pipeline</h5>

```text
New raw data
   ↓
pipeline.predict()
   ↓
Pipeline applies learned preprocessing
   ↓
Model
   ↓
Prediction
```

### One-line difference

> **Without Pipeline → you manage preprocessing yourself.**  
> **With Pipeline → the fitted Pipeline manages preprocessing + prediction together.**

### Final revision flow

```text
             ML PIPELINES
                   │
        ┌──────────┴──────────┐
        │                     │
   WITHOUT                  WITH
   Pipeline                Pipeline
        │                     │
manual preprocessing     preprocessing
        │                  + model
        ↓                     ↓
   model.predict()      pipeline.predict()
        │                     │
        └──────────┬──────────┘
                   ↓
               Prediction
```

Below are both uploaded prediction notebooks for direct comparison.

<h5 style="color:#78B89A; font-weight:bold;">A. Prediction WITHOUT Pipeline — uploaded example</h5>

In [19]:
import pickle
import numpy as np

In [20]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [21]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [22]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [23]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

In [24]:
test_input_sex

array([[0., 1.]])

In [25]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [26]:
test_input_embarked

array([[0., 0., 1.]])

In [14]:
test_input_age = test_input[:,2].reshape(1,1)

In [27]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [28]:
test_input_transformed.shape

(1, 10)

In [29]:
clf.predict(test_input_transformed)

array([1], dtype=int64)

<h5 style="color:#78B89A; font-weight:bold;">B. Prediction WITH Pipeline — uploaded example</h5>

In [20]:
import pickle
import numpy as np

In [21]:
pipe = pickle.load(open('pipe.pkl','rb'))

In [24]:
# Assume user input
test_input2 = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [25]:
pipe.predict(test_input2)

array([0], dtype=int64)

<h5 style="color:#78B89A; font-weight:bold;">Quick revision</h5>

```text
WITHOUT:
new data → manually preprocess → model.predict()

WITH:
new data → pipeline.predict()
```

**Pipeline = reusable preprocessing + model workflow.**